# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [9]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [11]:
# import csv
csv_path = "output_data/cities.csv"
# read csv
weather_df = pd.read_csv(csv_path)
weather_df

,Unnamed: 0,city,temp_max,humidity,clouds,windspeed,lat,lng,country,date
0,0,kalmunai,76.19,89,33,9.57,7.4167,81.8167,LK,1612747621
1,1,altay,21.06,81,66,3.49,47.8667,88.1167,CN,1612747621
2,2,chokurdakh,-15.34,88,100,7.94,70.6333,147.9167,RU,1612747373
3,3,qaanaaq,15.80,85,100,6.40,77.4840,-69.3632,GL,1612747365
4,4,morris,30.99,78,70,1.99,40.8334,-74.5329,US,1612747621
5,5,yuncheng,38.17,68,0,5.95,35.0231,110.9928,CN,1612747621
6,6,trairi,79.84,81,0,8.43,-3.2778,-39.2689,BR,1612747383
7,7,castro,58.23,67,0,7.05,-24.7911,-50.0119,BR,1612747515
8,8,lavrentiya,-8.16,86,0,8.41,65.5833,-171.0000,RU,1612747561
9,9,kitob,44.60,76,97,4.61,39.0843,66.8332,UZ,1612747622
10,10,bredasdorp,57.20,82,8,5.75,-34.5322,20.0403,ZA,1612747517
11,11,rikitea,77.63,71,47,12.50,-23.1203,-134.9692,PF,1612747518
12,12,santiago del estero,81.00,52,4,5.99,-27.7951,-64.2615,AR,1612747622
13,13,hovd,11.77,84,100,1.21,48.0056,91.6419,MN,1612747622
14,14,punta arenas,62.60,42,75,8.05,-53.1500,-70.9167,CL,1612747622
15,15,albany,26.01,54,79,5.01,42.6001,-73.9662,US,1612747622
16,16,andenes,30.20,74,100,6.91,69.3143,16.1194,NO,1612747622
17,17,hasaki,44.01,49,75,10.36,35.7333,140.8333,JP,1612747517
18,18,ushuaia,51.80,82,75,9.22,-54.8000,-68.3000,AR,1612747248
19,19,vila franca do campo,57.20,77,40,10.36,37.7167,-25.4333,PT,1612747623
20,20,najran,59.00,51,20,2.62,17.4924,44.1277,SA,1612747623
21,21,puerto ayora,77.00,96,100,1.99,-0.7393,-90.3518,EC,1612747516
22,22,san pablo tacachico,80.60,65,20,6.91,13.9756,-89.3400,SV,1612747623
23,23,tonj,64.87,26,28,6.38,7.2737,28.6822,SS,1612747623
24,24,banjar,82.40,83,40,4.61,-8.1900,114.9675,ID,1612747436
25,25,mahebourg,78.80,83,40,5.75,-20.4081,57.7000,MU,1612747357
26,26,bluff,63.75,62,100,7.05,-46.6000,168.3333,NZ,1612747623
27,27,yinchuan,31.03,79,100,4.74,38.4681,106.2731,CN,1612747624
28,28,yellowknife,-33.00,67,40,8.05,62.4560,-114.3525,CA,1612747624
29,29,mataura,73.42,42,100,3.15,-46.1927,168.8643,NZ,1612747350
30,30,port elizabeth,64.40,82,0,10.36,-33.9180,25.5701,ZA,1612747466
31,31,busselton,66.99,98,94,4.00,-33.6500,115.3333,AU,1612747379
32,32,upernavik,18.48,79,2,3.53,72.7868,-56.1549,GL,1612747351
33,33,clyde river,-5.80,84,40,11.50,70.4692,-68.5914,CA,1612747407
34,34,dickinson,54.00,76,20,9.22,29.4608,-95.0513,US,1612747624
35,35,sao filipe,68.88,74,100,12.66,14.8961,-24.4956,CV,1612747624
36,36,atuona,79.72,73,14,20.71,-9.8000,-139.0333,PF,1612747515
37,37,margate,32.00,76,100,8.01,51.3813,1.3862,GB,1612747625
38,38,vaini,77.00,100,90,12.66,-21.2000,-175.2000,TO,1612747355
39,39,new norfolk,61.00,64,100,1.99,-42.7826,147.0587,AU,1612747368
40,40,ntcheu,65.30,97,100,2.48,-14.8203,34.6359,MW,1612747625
41,41,karratha,81.90,63,1,12.19,-20.7377,116.8463,AU,1612747625
42,42,vestmanna,35.60,64,75,14.97,62.1564,-7.1664,FO,1612747625
43,43,mocuba,73.51,98,54,2.13,-16.8392,36.9856,MZ,1612747625
44,44,buala,85.03,75,97,9.22,-8.1450,159.5921,SB,1612747625
45,45,arraial do cabo,75.04,81,100,5.64,-22.9661,-42.0278,BR,1612747516

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [12]:
#configure gmaps
gmaps.configure(api_key=g_key)

In [15]:
# Store 'Lat' and 'Lng' into  locations 
locations = weather_df[["lat", "lng"]].astype(float)

# Convert humidity to float and store
humidity = weather_df["humidity"].astype(float)

In [16]:
# Create a humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [20]:
hotel_df = weather_df.loc[weather_df['temp_max']> 70].loc[weather_df['temp_max']<80] \
.loc[weather_df['windspeed']< 10].loc[weather_df['clouds']== 0]

hotel_df

,Unnamed: 0,city,temp_max,humidity,clouds,windspeed,lat,lng,country,date
6,6,trairi,79.84,81,0,8.43,-3.2778,-39.2689,BR,1612747383

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [24]:
# find the closest hotel for each set of coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():

    # get lat, lon from df
    lat = row["lat"]
    long = row["lng"]
    
    # add keyword to params dict
    params['location'] = f"{lat},{long}"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['city']}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 6: trairi.
Closest hotel is janelas do mar.
------------

In [25]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

KeyError: 'City'

In [26]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)

# Create hotel symbol layer
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info
)

# Display figure
# Add the layer to the map
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig

NameError: name 'hotel_info' is not defined

In [27]:
plt.savefig('hotel_heatmap.png')